name: titanic
dependencies:
  - python=3.6
  - category_encoders>=1.3.0
  - setuptools>=39.1.0
  - seaborn  # >=0.9.0
  - numpy  # >=1.16.0
  - statsmodels>=0.9.0
  - matplotlib>=2.2.2
  - nbformat>=4.4.0
  - pytest>=3.5.1
  - nbconvert>=5.3.1
  - pandas>=0.23.0
  - click>=6.7
  - scikit-learn>=0.20.2
  - datrie
  - pip:
    - kaggle>=1.5.1.1
    - snakemake>=5.4.0
